<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Purge</AssemblyName>
    <RootNamespace>Purge</RootNamespace>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>