<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>WebToMarkdown</AssemblyName>
    <RootNamespace>WebToMarkdown</RootNamespace>
    <EnableWindowsTargeting>false</EnableWindowsTargeting>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <StartupObject></StartupObject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>icoico.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Company>ICAZA MEDIA</Company>
    <Authors>ICAZA</Authors>
    <Description>Windows command-line web extraction</Description>
    <Copyright>MIT</Copyright>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icoico.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
